version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.7
    commands:
      - aws --version
      - echo Installing the depencies
      - pip install --upgrade pip
      - pip install -r src/requirements.txt -t ./src
  pre_build:
    commands:
      - sam --version
      - sam package --template-file ./template.yaml --output-template-file ./packaged.yaml --s3-bucket "sam-assignment" --region ap-south-1 
      - sam deploy --template-file ./packaged.yaml --stack-name GetIpData-green --capabilities CAPABILITY_IAM --region ap-south-1